server:
  port: 8483
  shutdown: graceful

spring:
  data:
    mongodb:
      database: processor
      uri: mongodb://localhost:27017

tibiacalcs:
  online-players:
    worlds: Honbra

#logging:
  # level:
    # org.springframework.data.mongodb.core.MongoTemplate: debug
